FROM ubuntu:22.04

ARG DEBIAN_FRONTEND=noninteractive
ARG mscpdir="/mscp"

COPY . ${mscpdir}

RUN set -ex && apt-get update && apt-get install -y --no-install-recommends \
	ca-certificates

RUN ${mscpdir}/install-build-deps.sh

RUN cd ${mscpdir}	\
	&& rm -rf build

RUN cd ${mscpdir}	\
	&& cmake -B build -DBUILD_PKG=1	\
	&& cd ${mscpdir}/build		\
	&& cpack -G DEB CPackConfig.cmake 
